# Configuración de Netlify para prevenir clonación y mejorar seguridad

[build]
  publish = "dist"
  command = "npm run build"

# Redirecciones y reescrituras
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin", "cms"]}

# Redirección para prevenir acceso a archivos sensibles
[[redirects]]
  from = "/.env"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/.git/*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/wp-admin/*"
  to = "/404.html"
  status = 404
  force = true

# Cabeceras de seguridad adicionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), autoplay=(), display-capture=(), document-domain=(), encrypted-media=(), fullscreen=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; object-src 'none'; upgrade-insecure-requests; block-all-mixed-content"
    Cache-Control = "no-store, max-age=0"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Feature-Policy = "accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'"

# Cabeceras específicas para archivos JavaScript
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

# Cabeceras específicas para archivos CSS
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

# Cabeceras específicas para imágenes
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de funciones de Netlify
[functions]
  directory = "netlify/functions"

# Configuración de plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # Configuraciones opcionales
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

# Configuración de entorno
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"